name: Code Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main, develop

env:
  GITHUB_TOKEN : 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
  SONAR_TOKEN : 1affd398034bd9c7d0049bcdef6fbdc624b51344
  SONAR_SERVER : http://ec2-3-135-236-218.us-east-2.compute.amazonaws.com:9000
  DEFECT_DOJO_TOKEN: 0dfc2ae06f011369f4eefbcf3e067efb9627ce09
      
jobs:
  SonarScanner:
    runs-on: ubuntu-latest
    name: Sonar Scanner
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn install --production=false
      - name: Scan code
        uses: vtex/action-sonarqube@main
        with:
          githubToken: ${{ env.GITHUB_TOKEN }}
          host: ${{ env.SONAR_SERVER }} 
          token: ${{ env.SONAR_TOKEN }} 
          
      - name: Create new engagement
        id: engagements
        uses: ivanamat/defectdojo-engagements@v1
        with:
          token: 0dfc2ae06f011369f4eefbcf3e067efb9627ce09
          defectdojo_url: http://ec2-3-135-244-217.us-east-2.compute.amazonaws.com:8080/
          defectdojo_endpoint:  http://ec2-3-135-244-217.us-east-2.compute.amazonaws.com:8080/api/v2/engagements/
          name: gastonbarbaccia-test
          description: gastonbarbaccia-test
          version: ''
          target_start: ''
          target_end: ''
          product: 3
      - name: Show response
        run: |
          set -e
          printf '%s\n' '${{ steps.engagements.outputs.response }}'
      
