name: Code Scanning

on:
  push:
    branches:
      - main
      - develop
      - zap_proxy
  pull_request:
    branches:
      - main
      - develop
      - zap_proxy
env:
  GITHUB_TOKEN : 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
  SONAR_TOKEN : 1affd398034bd9c7d0049bcdef6fbdc624b51344
  SONAR_SERVER : http://ec2-3-20-205-255.us-east-2.compute.amazonaws.com:9000
  DEFECTDOJO_SERVER : http://ec2-18-223-247-63.us-east-2.compute.amazonaws.com:8080
      
jobs:
  zap_scan:
      runs-on: ubuntu-latest
      name: Test 1
      continue-on-error: true
      steps:
        - uses: actions/checkout@v1
        - name: Add SHORT_SHA env property with commit short sha
          run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
        - name: My step 1
          run: echo Test1_${SHORT_SHA}

  zap_scan2:
      runs-on: ubuntu-latest
      name: Test 2
      continue-on-error: true
      steps:
        - name: Add SHORT_SHA env property with commit short sha
          run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
        - name: My step 2
          run: echo Test1_${SHORT_SHA}