name: Code Scanning

on:
  push:
    branches:
      - main
      - develop
      - zap_proxy
  pull_request:
    branches:
      - main
      - develop
      - zap_proxy
env:
  GITHUB_TOKEN : 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
  SONAR_TOKEN : 1affd398034bd9c7d0049bcdef6fbdc624b51344
  SONAR_SERVER : http://ec2-3-20-205-255.us-east-2.compute.amazonaws.com:9000
  DEFECTDOJO_SERVER : http://ec2-18-223-247-63.us-east-2.compute.amazonaws.com:8080
      
jobs:
  zap_scan:
      runs-on: ubuntu-latest
      name: Test
      continue-on-error: true
      steps:
        - uses: actions/checkout@v1

        - name: Get Branch
          id: branch
          run: echo "git_branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_BRANCH

        - name: Check Branch
          run: echo "${{ env.branch }}"

        - name: Get Hash
          id: hash
          run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_HASH

        - name: Check Hash
          run: echo "${{ env.hash }}"