name: Code Scanning

on:
  push:
    branches:
      - main
      - develop
      - mobsfscan
  pull_request:
    branches:
      - main
      - develop
      - mobsfscan

env:
  GITHUB_TOKEN : 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
  SONAR_TOKEN : 1affd398034bd9c7d0049bcdef6fbdc624b51344
  SONAR_SERVER : http://ec2-3-20-205-255.us-east-2.compute.amazonaws.com:9000
  DEFECTDOJO_SERVER : http://ec2-18-223-247-63.us-east-2.compute.amazonaws.com:8080
      
jobs:                 
  mobsfscan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: mobsfscan
      uses: MobSF/mobsfscan@main
      with:
        args: '--json --output results_mobile.json .'

