name: Code Scanning

on:
  push:
    branches:
      - main
      - develop
      - zap_proxy
  pull_request:
    branches:
      - main
      - develop
      - zap_proxy
env:
  GITHUB_TOKEN : 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
  SONAR_TOKEN : 1affd398034bd9c7d0049bcdef6fbdc624b51344
  SONAR_SERVER : http://ec2-3-20-205-255.us-east-2.compute.amazonaws.com:9000
  DEFECTDOJO_SERVER : http://ec2-18-223-247-63.us-east-2.compute.amazonaws.com:8080
      
jobs:
  zap_scan:
      runs-on: ubuntu-latest
      name: Scan ZAP website
      continue-on-error: true
      steps:
        - name: ZAP Scan
          uses: gastonbarbaccia/zapproxy@v0.1.1
          with:
            target: 'https://devsecops-test.herokuapp.com/'
        - name: Branch SHA
        - run: |
                BRANCH_NAME=$(echo $GITHUB_REF | cut -d'/' -f 3)
                GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)
                echo BRANCH_NAME_GITHUB_SHA_SHORT